services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py loaddata sample_planetarium.json &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./media:/vol/web/media
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data: